pianoschool/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('modal/', views.modal, name='modal'),
    path('klavesin/', views.klavesin, name='klavesin'),
    path('organ/', views.organ, name='organ')
]

pianoschool/pianoschool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('school/', include('school.urls')),
]

pianoschool/school/urls.py
from . import views
from .views import TestDetailView, TestResultSubmitView, ExportProgressReportView
from django.urls import path
from .views import student_progress
from .views import TeacherStudentsView, StudentProgressDetailView


app_name = 'school'

urlpatterns = [
    # URL для страницы с уроками сольфеджио
    path('solfeggio/', views.SolfeggioLessonsView.as_view(), name='solfeggio_lessons'),
    path('solfeggio/lesson/<int:pk>/', views.LessonSolfDetailView.as_view(), name='lesson_detail_solf'),
    path('test/<int:pk>/', TestDetailView.as_view(), name='test_detail'),
    path('test/<int:pk>/submit/', TestResultSubmitView.as_view(), name='test_result_submit'),
    path('progress/', student_progress, name='student_progress'),
    path('teacher/students/', TeacherStudentsView.as_view(), name='teacher_students'),
    path('teacher/student/<int:pk>/progress/', StudentProgressDetailView.as_view(), name='student_progress_detail'),
    path("tests/", views.test_list, name="test_list"),
    path('literature-lessons/', views.LiteratureLessonsView.as_view(), name='literature_lessons'),
    path('literature-lessons/lesson/<int:pk>/', views.LessonLiteratureDetailView.as_view(), name='lesson_detail_lit'),
    path('export-progress/', ExportProgressReportView.as_view(), name='export_progress_report'),

    path('ear_training_tests/', views.ear_training_tests, name='ear_training_tests'),
    path('ear_training_test/<int:test_id>/', views.ear_training_test_detail, name='ear_training_test_detail'),
    path('ear_training_test/<int:test_id>/task/<int:task_id>/', views.ear_training_task, name='ear_training_task'),
    path('submit_attempt/', views.submit_attempt, name='submit_attempt'),
    path('ear_training_test/<int:test_id>/result/', views.ear_training_test_result, name='ear_training_test_result'),
    path('ear_training_results/<str:section_name>/', views.ear_training_results_section,name='ear_training_results_section'),

]

pianoschool/main/models.py
from django.db import models

pianoschool/main/views.py
from django.shortcuts import render, redirect


def index(request):
    return render(request, 'main/index.html')


def modal(request):
    return render(request, 'main/modal.html')

def klavesin(request):
    return render(request, 'main/klavesin.html')
def organ(request):
    return render(request, 'main/organ.html')

pianoschool/main/templates/main/index.html
{% extends 'main/layout.html'%}
{% block title %}
    Главная
{%endblock%}
{% block content %}
{% load static %}
<div class="contents container">
  <div class="row">
      <div class="col-lg-3 col-md-12 order-md-1 mb-4">
      <menu class="w-100">
        <h2>Меню</h2>
        <ul>
            <li><a href="{% url 'personalisation'%}">Личный кабинет</a></li>
            {% if user.is_authenticated %}
                {% load group_filters %}
                {% if user|has_group:"Ученики" %}
                    <li><a href="{% url 'school:student_progress' %}">Мой прогресс</a></li>
                    <li><a href="{% url 'school:ear_training_tests' %}">Слуховые контрольные</a></li>
                {% endif %}
                {% if user|has_group:"Учителя" %}
                    <li><a href="{% url 'school:teacher_students' %}">Мои ученики</a></li>
                {% endif %}
                {% if user|has_group:"Учителя" %}
                    <li><a href="{% url 'school:export_progress_report' %}">Выгрузить отчет</a></li>
                {% endif %}
            {% endif %}
            <div>Уроки:</div>
            <ul>
                <li><a href="{% url 'school:literature_lessons'%}">Музыкальная литература</a></li>
                <li><a href="{% url 'school:solfeggio_lessons'%}">Сольфеджио</a></li>
            </ul>
            <div>Инструменты:</div>
            <ul>
                <li><a href="{% url 'home'%}">Пианино</a></li>
                <li><a href="{% url 'klavesin'%}">Клавесин</a></li>
                <li><a href="{% url 'organ'%}">Орган</a></li>
            </ul>
            <li><a href="{% url 'school:test_list'%}">Тесты</a></li>
        </ul>
    </menu>
      </div>

            <!-- Виртуальное пианино -->
        <div class="card shadow-sm col-lg-9 col-md-12 order-md-2 mb-4">
            <div class="card-header accent-bg">
                <h2 class="h5 mb-0">Виртуальное пианино</h2>
            </div>
            <div class="card-body">
                <div class="piano">
                    <div class="container" style="width: 100%;">
                        <div class="keys">
                            <button class="col-xl col-md col-sm key key-w C " data-sound="C">До</button>
                            <button class="col-xl col-md col-sm key key-b Cs " data-sound="Cs">До# <br> РеЬ</button>
                            <button class="col-xl col-md col-sm key key-w D " data-sound="D">Ре</button>
                            <button class="col-xl col-md col-sm key key-b Ds " data-sound="Ds">Ре# <br> МиЬ</button>
                            <button class="col-xl col-md col-sm key key-w E " data-sound="E">Ми</button>
                            <button class="col-xl col-md col-sm key key-w F " data-sound="F">Фа</button>
                            <button class="col-xl col-md col-sm key key-b Fs " data-sound="Fs">Фа# <br> СольЬ</button>
                            <button class="col-xl col-md col-sm key key-w G " data-sound="G">Соль</button>
                            <button class="col-xl col-md col-sm key key-b Gs " data-sound="Gs">Соль# <br> ЛяЬ</button>
                            <button class="col-xl col-md col-sm key key-w A " data-sound="A">Ля</button>
                            <button class="col-xl col-md col-sm key key-b As " data-sound="As">Ля# <br> СиЬ</button>
                            <button class="col-xl col-md col-sm key key-w B " data-sound="B">Си</button>
                            <button class="col-xl col-md col-sm key key-w C1 " data-sound="C1">До</button>
                            <button class="col-xl col-md col-sm key key-b Cs1 " data-sound="Cs1">До# <br> РеЬ</button>
                            <button class="col-xl col-md col-sm key key-w D1 " data-sound="D1">Ре</button>
                            <button class="col-xl col-md col-sm key key-b Ds1 " data-sound="Ds1">Ре# <br> МиЬ</button>
                            <button class="col-xl col-md col-sm key key-w E1 " data-sound="E1">Ми</button>
                            <button class="col-xl col-md col-sm key key-w F1 " data-sound="F1">Фа</button>
                            <button class="col-xl col-md col-sm key key-b Fs1 " data-sound="Fs1">Фа# <br> СольЬ</button>
                            <button class="col-xl col-md col-sm key key-w G1 " data-sound="G1">Соль</button>
                            <button class="col-xl col-md col-sm key key-b Gs1 " data-sound="Gs1">Соль# <br> ЛяЬ</button>
                            <button class="col-xl col-md col-sm key key-w A1 " data-sound="A1">Ля</button>
                            <button class="col-xl col-md col-sm key key-b As1 " data-sound="As1">Ля# <br> СиЬ</button>
                            <button class="col-xl col-md col-sm key key-w B1 " data-sound="B1">Си</button>
                            <button class="col-xl col-md col-sm key key-w C2" data-sound="C2">До</button>
                            <button class="col-xl col-md col-sm key key-b Cs2" data-sound="Cs2">До# <br> РеЬ</button>
                            <button class="col-xl col-md col-sm key key-w D2 " data-sound="D2">Ре</button>
                            <button class="col-xl col-md col-sm key key-b Ds2 " data-sound="Ds2">Ре# <br> МиЬ</button>
                            <button class="col-xl col-md col-sm key key-w E2 " data-sound="E2">Ми</button>
                            <button class="col-xl col-md col-sm key key-w F2 " data-sound="F2">Фа</button>
                            <button class="col-xl col-md col-sm key key-b Fs2 " data-sound="Fs2">Фа# <br> СольЬ</button>
                            <button class="col-xl col-md col-sm key key-w G2 " data-sound="G2">Соль</button>
                            <button class="col-xl col-md col-sm key key-b Gs2 " data-sound="Gs2">Соль# <br> ЛяЬ</button>
                            <button class="col-xl col-md col-sm key key-w A2 " data-sound="A2">Ля</button>
                            <button class="col-xl col-md col-sm key key-b As2 " data-sound="As2">Ля# <br> СиЬ</button>
                            <button class="col-xl col-md col-sm key key-w B2 " data-sound="B2">Си</button>
                            <audio id="C" >
                                <source src="{% static 'audio1/c2.mp3'%}" type="audio/mpeg" />
                            </audio>
                            <audio id="Cs" >
                                <source src="{% static 'audio1/cs2.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="D" >
                                <source src="{% static 'audio1/d2.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="Ds" >
                                <source src="{% static 'audio1/ds2.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="E" >
                                <source src="{% static 'audio1/e2.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="F" >
                                <source src="{% static 'audio1/f2.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="Fs" >
                                <source src="{% static 'audio1/fs2.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="G" >
                                <source src="{% static 'audio1/g2.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="Gs" >
                                <source src="{% static 'audio1/gs2.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="A" >
                                <source src="{% static 'audio1/a2.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="As" >
                                <source src="{% static 'audio1/as2.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="B" >
                                <source src="{% static 'audio1/b2.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="C1" >
                                <source src="{% static 'audio1/c3.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="Cs1" >
                                <source src="{% static 'audio1/cs3.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="D1" >
                                <source src="{% static 'audio1/d3.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="Ds1" >
                                <source src="{% static 'audio1/ds3.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="E1" >
                                <source src="{% static 'audio1/e3.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="F1" >
                                <source src="{% static 'audio1/f3.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="Fs1" >
                                <source src="{% static 'audio1/fs3.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="G1" >
                                <source src="{% static 'audio1/g3.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="Gs1" >
                                <source src="{% static 'audio1/gs3.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="A1" >
                                <source src="{% static 'audio1/a3.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="As1" >
                                <source src="{% static 'audio1/as3.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="B1" >
                                <source src="{% static 'audio1/b3.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="C2" >
                                <source src="{% static 'audio1/c4.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="Cs2" >
                                <source src="{% static 'audio1/cs4.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="D2" >
                                <source src="{% static 'audio1/d4.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="Ds2" >
                                <source src="{% static 'audio1/ds4.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="E2" >
                                <source src="{% static 'audio1/e4.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="F2" >
                                <source src="{% static 'audio1/f4.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="Fs2" >
                                <source src="{% static 'audio1/fs4.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="G2" >
                                <source src="{% static 'audio1/g4.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="Gs2" >
                                <source src="{% static 'audio1/gs4.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="A2" >
                                <source src="{% static 'audio1/a4.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="As2" >
                                <source src="{% static 'audio1/as4.mp3'%}" type="audio/mpeg"/>
                            </audio>
                            <audio id="B2" >
                                <source src="{% static 'audio1/b4.mp3'%}" type="audio/mpeg"/>
                            </audio>
                        </div>
                    </div>
                </div>
                <div class="mt-3">
                    <p class="small text-muted">Используйте мышь или клавиатуру для игры на пианино.</p>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
    </div>
{%endblock%}
{% block extra_js %}
    <script src="{% static 'main/js/index.js' %}" defer></script>
{% endblock %}

pianoschool/main/templates/main/layout.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link href="{% static 'main/css/layout.css'%}" rel="stylesheet" type="text/css">

	<link href="{% static 'main/css/layout1.css' %}" rel="stylesheet">

    <link href="{% static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
	<script src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
	<link href="{% static 'bootstrap/css/bootstrap-reboot.css'%}" rel="stylesheet">
	<link href="{% static 'bootstrap/css/bootstrap-grid.min.css'%}" rel="stylesheet">
	{% block extra_css %}
	{% endblock %}

	<script defer type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
	<script defer type="text/javascript" src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

    <title>  {% block title %}{% endblock %}</title>
</head>
<body>
	<div class="content">
		<header>
			<nav class="navbar-nav">
				<div class="navbar__container">
					<a href="{% url 'home' %}" class="navbar__container-brand">PianoSchool</a>
					<div class="navbar__container-wrap">
						<ul class="navbar__container-wrap-menu">
							<li><a href="{% url 'home' %}">На главную </a> | </li>
							{% if request.user.is_authenticated %}
								<li>{{user.username}} | <a href="{% url 'logout' %}">Выйти</a></li>
							{% else %}
							<li><a href="{% url 'register' %}">Регистрация</a></li>
							<li><a href="{% url 'login' %}">Войти</a></li>
							{% endif %}
						</ul>
						<a href="{% url 'modal' %}" class="navbar__container-wrap-callback">
							<span>Как играть?</span>
						</a>
					</div>
					<div class="burger-menu" id="burgerMenu">
    <button class="burger-icon" id="burgerBtn" aria-label="Открыть меню" aria-expanded="false">
        <span></span>
        <span></span>
        <span></span>
    </button>
    <nav class="menu-dropdown" id="menuDropdown" aria-label="Меню сайта">
        <h2>Меню</h2>
        <ul>
            <li><a href="{% url 'personalisation'%}">Личный кабинет</a></li>
            {% if user.is_authenticated %}
                {% load group_filters %}
                {% if user|has_group:"Ученики" %}
                    <li><a href="{% url 'school:student_progress' %}">Мой прогресс</a></li>
					<li><a href="{% url 'school:ear_training_tests' %}">Слуховые контрольные</a></li>
                {% endif %}
                {% if user|has_group:"Учителя" %}
                    <li><a href="{% url 'school:teacher_students' %}">Мои ученики</a></li>
                {% endif %}
				{% if user|has_group:"Учителя" %}
                    <li><a href="{% url 'school:export_progress_report' %}">Выгрузить отчет</a></li>
                {% endif %}
            {% endif %}
        </ul>
        <div class="menu-section-title">Уроки:</div>
        <ul>
            <li><a href="{% url 'school:literature_lessons'%}">Музыкальная литература</a></li>
            <li><a href="{% url 'school:solfeggio_lessons'%}">Сольфеджио</a></li>
        </ul>
        <div class="menu-section-title">Инструменты:</div>
        <ul>
            <li><a href="{% url 'home'%}">Пианино</a></li>
            <li><a href="{% url 'klavesin'%}">Клавесин</a></li>
            <li><a href="{% url 'organ'%}">Орган</a></li>
        </ul>
        <ul>
            <li><a href="{% url 'school:test_list'%}">Тесты</a></li>
        </ul>
    </nav>
</div>
				</div>
			</nav>
		</header>
	</div>
	<main>
	{% block content %}
  	{% endblock %}
	</main>
	<footer class="footer" role="contentinfo">
		<div class="container-fluid">
			<div class="row">
				<p>Проект Копанецкой Анастасии "Образовательная платформа для обучения в музыкальных школах", Краснодар, Россия, 2025.<br></p>
			</div>
		</div>
	</footer>
	{% block extra_js %}
  	{% endblock %}
    <script src="{% static 'main/js/layout.js' %}" defer></script>
</body>
</html>